name: Push-to-EC2

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          REMOTE_HOST: "ec2-44-211-246-156.compute-1.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/wepad_test_app"

      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
         remote_host:  ubuntu@ec2-44-211-246-156.compute-1.amazonaws.com
         args: docker stack deploy -c docker-compose.yml local-test
